// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AddDownloadRecordReq struct {
	DownloadId string `form:"download_id"`
	Type       string `form:"type"`
}

type AddDownloadRecordRes struct {
	Base
}

type AddSearchRecordsReq struct {
	Keywords string `form:"keywords"`
}

type AddSearchRecordsRes struct {
	Base
}

type Album struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	Desc      string `json:"desc"`
	Cover     string `json:"cover"`
	CoverPath string `json:"cover_path"`
	Status    bool   `json:"status"`
}

type AlbumCreateReq struct {
	Name   string `json:"name"`
	Desc   string `json:"desc"`
	Cover  string `json:"cover"`
	Status bool   `json:"status"`
}

type AlbumCreateRes struct {
	Base
}

type AlbumDetailData struct {
	BaseRecord
	Records []AlbumImageInfo `json:"records"`
}

type AlbumDetailReq struct {
	Id string `form:"id"`
	BasePage
}

type AlbumDetailRes struct {
	Base
	Data AlbumDetailData `json:"data"`
}

type AlbumImageInfo struct {
	Id       string `json:"id"`
	FileName string `json:"file_name"`
	FilePath string `json:"file_path"`
}

type AlbumListData struct {
	BaseRecord
	Records []Album `json:"records"`
}

type AlbumListReq struct {
	BasePage
}

type AlbumListRes struct {
	Base
	Data AlbumListData `json:"data"`
}

type AlbumRemoveReq struct {
	Id int64 `json:"id"`
}

type AlbumRemoveRes struct {
	Base
}

type AlbumUpdateReq struct {
	Id     string `json:"id"`
	Name   string `json:"name"`
	Desc   string `json:"desc"`
	Cover  string `json:"cover"`
	Status bool   `json:"status"`
}

type AlbumUpdateRes struct {
	Base
}

type Base struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type BasePage struct {
	Page  int `form:"page"`
	Limit int `form:"limit"`
}

type BaseRecord struct {
	Page  int   `json:"page"`
	Limit int   `json:"limit"`
	Total int64 `json:"total"`
}

type BaseResp struct {
}

type BaseTime struct {
	Created int64 `json:"created"`
	Updated int64 `json:"updated"`
}

type BlockCreateReq struct {
	TargetId string `json:"target_id"`
	Type     string `json:"type"`
}

type BlockCreateRes struct {
	Base
}

type BlockDataInfo struct {
	Id             string `json:"id"`
	TargetId       string `json:"target_id"`
	Title          string `json:"title"`
	Type           string `json:"type"`
	OriginFilePath string `json:"origin_file_path"`
	FilePath       string `json:"file_path"`
	W              int    `json:"w"`
	H              int    `json:"h"`
}

type BlockListData struct {
	BaseRecord
	Records []BlockListInfo `json:"records"`
}

type BlockListInfo struct {
	BaseTime
	Id            string        `json:"id"`
	BlockUserInfo BlockUserInfo `json:"block_user_info"`
	BlockDataInfo BlockDataInfo `json:"block_data_info"`
}

type BlockListReq struct {
	BasePage
	Type string `form:"type"`
}

type BlockListRes struct {
	Base
	Data BlockListData `json:"data"`
}

type BlockRemoveReq struct {
	Id string `form:"id"`
}

type BlockRemoveRes struct {
	Base
}

type BlockUserInfo struct {
	Id         string `json:"id"`
	Username   string `json:"username"`
	UserAvatar string `json:"user_avatar"`
}

type CancelAccountReq struct {
}

type CancelAccountRes struct {
	Base
}

type CarouselCreateReq struct {
	Path   string `json:"path"`
	Sort   int    `json:"sort"`
	Status int    `json:"status"`
}

type CarouselCreateRes struct {
	Base
}

type CarouselInfo struct {
	Id     string `json:"id"`
	Path   string `json:"path"`
	Sort   int    `json:"sort"`
	Status int    `json:"status"`
}

type CarouselListData struct {
	BaseRecord
	Records []CarouselInfo `json:"records"`
}

type CarouselListReq struct {
	BasePage
	Status int `form:"status"`
}

type CarouselListRes struct {
	Base
	Data CarouselListData `json:"data"`
}

type CarouselRemoveReq struct {
	Id string `json:"id"`
}

type CarouselRemoveRes struct {
	Base
}

type CarouselUpdateReq struct {
	Id     string `json:"id"`
	Path   string `json:"path"`
	Sort   int    `json:"sort"`
	Status int    `json:"status"`
}

type CarouselUpdateRes struct {
	Base
}

type CategoryCreateReq struct {
	Name string `json:"name"`
	Sort int    `json:"sort"`
	Web  bool   `json:"web"`
	Moa  bool   `json:"moa"`
}

type CategoryCreateRes struct {
	Base
}

type CategoryInfo struct {
	BaseRecord
	Id   string `json:"id"`
	Name string `json:"name"`
	Sort int    `json:"sort"`
	Web  bool   `json:"web"`
	Moa  bool   `json:"moa"`
}

type CategoryInfoData struct {
	BaseRecord
	Records []CategoryInfo `json:"records"`
}

type CategoryInfoReq struct {
	BasePage
	Name string `form:"name,optional"`
}

type CategoryInfoRes struct {
	Base
	Data CategoryInfoData `json:"data"`
}

type CategoryRemoveReq struct {
	Id string `json:"id"`
}

type CategoryRemoveRes struct {
	Base
}

type CategorySortInfo struct {
	Id   string `json:"id"`
	Sort int    `json:"sort"`
}

type CategorySortReq struct {
	SortData []CategorySortInfo `json:"sort_data"`
}

type CategorySortRes struct {
	Base
}

type CategorySummary struct {
	BaseRecord
	Id     string                      `json:"id"`
	Name   string                      `json:"name"`
	Upload []CategorySummaryUploadInfo `json:"upload"`
}

type CategorySummaryListData struct {
	BaseRecord
	Records []CategorySummary `json:"records"`
}

type CategorySummaryListReq struct {
	BasePage
	Type string `form:"type"`
	Web  bool   `form:"web,optional"`
	Moa  bool   `form:"moa,optional"`
}

type CategorySummaryListRes struct {
	Base
	Data CategorySummaryListData `json:"data"`
}

type CategorySummaryUploadInfo struct {
	Id string `json:"id"`
}

type CategoryUpdateReq struct {
	Id   string `json:"id"`
	Name string `json:"name"`
	Sort int    `json:"sort"`
	Web  bool   `json:"web"`
	Moa  bool   `json:"moa"`
}

type CategoryUpdateRes struct {
	Base
}

type CommentCreateData struct {
	Id string `json:"id"`
}

type CommentCreateReq struct {
	PostId  string `json:"post_id"`
	Content string `json:"content"`
}

type CommentCreateRes struct {
	Base
	Data CommentCreateData `json:"data"`
}

type CommentDeleteReq struct {
	Id string `json:"id"`
}

type CommentDeleteRes struct {
	Base
}

type CommentInfo struct {
	BaseTime
	Id       string          `json:"id"`
	Content  string          `json:"content"`
	UserInfo CommentUserInfo `json:"user_info"`
}

type CommentListData struct {
	BaseRecord
	Records []CommentInfo `json:"records"`
}

type CommentListReq struct {
	BasePage
	PostId string `form:"post_id"`
}

type CommentListRes struct {
	Base
	Data CommentListData `json:"data"`
}

type CommentReviewListData struct {
	BaseRecord
	Records []CommentReviewListItem `json:"records"`
}

type CommentReviewListItem struct {
	BaseTime
	Id           string          `json:"id"`
	PostId       string          `json:"post_id"`
	PostTitle    string          `json:"post_title"`
	Content      string          `json:"content"`
	Status       int             `json:"status"`
	RejectReason string          `json:"reject_reason"`
	UserInfo     CommentUserInfo `json:"user_info"`
}

type CommentReviewListReq struct {
	BasePage
	Status int `form:"status,optional"` // 0=全部 2=待审核 1=已通过 -1=已拒绝
}

type CommentReviewListRes struct {
	Base
	Data CommentReviewListData `json:"data"`
}

type CommentReviewUpdateReq struct {
	Id           string `json:"id"`
	Status       int    `json:"status"` // 1=通过 -1=拒绝
	RejectReason string `json:"reject_reason,optional"`
}

type CommentReviewUpdateRes struct {
	Base
}

type CommentUserInfo struct {
	Id       string `json:"id"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}

type CommunityFeedData struct {
	BaseRecord
	Records []CommunityFeedInfo `json:"records"`
}

type CommunityFeedInfo struct {
	BaseTime
	Id        string            `json:"id"`
	FileName  string            `json:"file_name"`
	FilePath  string            `json:"file_path"`
	W         int               `json:"w"`
	H         int               `json:"h"`
	Type      string            `json:"type"`
	View      int               `json:"view"`
	Download  int               `json:"download"`
	LikeCount int64             `json:"like_count"`
	UserInfo  CommunityUserInfo `json:"user_info"`
}

type CommunityFeedReq struct {
	BasePage
	Sort string `form:"sort,optional"` // "hot" | "new", default "new"
	Type string `form:"type,optional"` // "pc" | "moa", empty = all
}

type CommunityFeedRes struct {
	Base
	Data CommunityFeedData `json:"data"`
}

type CommunityUserInfo struct {
	Id       string `json:"id"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}

type CreateTagReq struct {
	Name string `json:"name"`
	Type string `json:"type"`
	Sort int    `json:"sort"`
}

type CreateTagRes struct {
	Base
}

type DailyCreateReq struct {
	UploadId    string `json:"upload_id"`
	Date        string `json:"date"`
	Description string `json:"description,optional"`
}

type DailyCreateRes struct {
	Base
}

type DailyDeleteReq struct {
	Id string `json:"id"`
}

type DailyDeleteRes struct {
	Base
}

type DailyInfoData struct {
	Id             string   `json:"id"`
	FilePath       string   `json:"file_path"`
	FileName       string   `json:"file_name"`
	W              int      `json:"w"`
	H              int      `json:"h"`
	Date           string   `json:"date"`
	Edition        int      `json:"edition"`
	Description    string   `json:"description"`
	DownloadsToday int      `json:"downloads_today"`
	Tags           []string `json:"tags,optional"`
	PrevDate       string   `json:"prev_date,optional"`
	NextDate       string   `json:"next_date,optional"`
}

type DailyInfoReq struct {
	Date string `form:"date,optional"`
}

type DailyInfoRes struct {
	Base
	Data DailyInfoData `json:"data,optional"`
}

type DailyListData struct {
	BaseRecord
	Records []DailyListInfo `json:"records"`
}

type DailyListInfo struct {
	BaseTime
	DailyId     string `json:"daily_id"`
	Id          string `json:"id"`
	FilePath    string `json:"file_path"`
	FileName    string `json:"file_name"`
	Date        string `json:"date"`
	Edition     int    `json:"edition"`
	Description string `json:"description"`
	W           int    `json:"w"`
	H           int    `json:"h"`
}

type DailyListReq struct {
	BasePage
}

type DailyListRes struct {
	Base
	Data DailyListData `json:"data"`
}

type DailyUpdateReq struct {
	Id          string `json:"id"`
	UploadId    string `json:"upload_id,optional"`
	Date        string `json:"date,optional"`
	Description string `json:"description,optional"`
	Status      int    `json:"status,optional"`
}

type DailyUpdateRes struct {
	Base
}

type DiscoverCreateReq struct {
	Title    string `json:"title,optional"`
	Subtitle string `json:"subtitle,optional"`
	ImageIds string `json:"image_ids"`
}

type DiscoverCreateRes struct {
	Base
}

type DiscoverListData struct {
	BaseRecord
	Records []DiscoverListInfo `json:"records"`
}

type DiscoverListImages struct {
	Id       string `json:"id"`
	FilePath string `json:"file_path"`
	FileName string `json:"file_name"`
	W        int    `json:"w"`
	H        int    `json:"h"`
	Type     string `json:"type"`
}

type DiscoverListInfo struct {
	BaseTime
	Id       string               `json:"id"`
	Title    string               `json:"title"`
	Subtitle string               `json:"subtitle"`
	Status   int                  `json:"status"`
	Images   []DiscoverListImages `json:"images"`
	UserInfo DiscoverUserInfo     `json:"user_info"`
}

type DiscoverListReq struct {
	BasePage
	UserId string `form:"user_id,optional"`
	Status int    `form:"status,optional"`
	Sort   string `form:"sort,optional"`
}

type DiscoverListRes struct {
	Base
	Data DiscoverListData `json:"data"`
}

type DiscoverRemoveReq struct {
	Id string `form:"id"`
}

type DiscoverRemoveRes struct {
	Base
}

type DiscoverUpdateStatusReq struct {
	Id     string `json:"id"`
	Status int    `json:"status"`
}

type DiscoverUpdateStatusRes struct {
	Base
}

type DiscoverUserInfo struct {
	Id       string `json:"id"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}

type DownLoadUserListRecord struct {
	BaseTime
	Id       string `json:"id"`
	FileId   string `json:"file_id"`
	FilePath string `json:"file_path"`
	FileName string `json:"file_name"`
	W        int    `json:"w"`
	H        int    `json:"h"`
	Type     string `json:"type"`
}

type DownlaodUserListReq struct {
	BasePage
	Type string `form:"type,optional"`
}

type DownlaodUserListRes struct {
	Base
	Data DownloadUserListData `json:"data"`
}

type DownloadRemoveReq struct {
	Id string `json:"id"`
}

type DownloadRemoveRes struct {
	Base
}

type DownloadUrlData struct {
	Id             string `json:"id"`
	FileName       string `json:"file_name"`
	OriginType     string `json:"origin_type"`
	OriginFilePath string `json:"origin_file_path"`
	Type           string `json:"type"`
}

type DownloadUrlReq struct {
	Id string `form:"id"`
}

type DownloadUrlRes struct {
	Base
	Data DownloadUrlData `json:"data"`
}

type DownloadUserListData struct {
	BaseRecord
	Records []DownLoadUserListRecord `json:"records"`
}

type FeedbackCreateReq struct {
	FeedbackId string `json:"feedback_id"`
	Content    string `json:"content"`
	Type       string `json:"type"`
}

type FeedbackCreateRes struct {
	Base
}

type FeedbackInfo struct {
	BaseTime
	Id         string `json:"id"`
	FeedbackId string `json:"feedback_id"`
	Content    string `json:"content"`
	Type       string `json:"type"`
	Status     string `json:"status"`
	UserId     string `json:"user_id"`
}

type FeedbackListData struct {
	BaseRecord
	Records []FeedbackInfo `json:"records"`
}

type FeedbackListReq struct {
	BasePage
	Status string `form:"status,optional"`
}

type FeedbackListRes struct {
	Base
	Data FeedbackListData `json:"data"`
}

type FeedbackUpdateReq struct {
	Id     string `json:"id"`
	Status string `json:"status"`
}

type FeedbackUpdateRes struct {
	Base
}

type GroupCreateReq struct {
	Name string `json:"name"`
}

type GroupCreateRes struct {
	Base
}

type GroupListData struct {
	BaseRecord
	Records []GroupListInfo `json:"records"`
}

type GroupListInfo struct {
	BaseTime
	Id   string `json:"id"`
	Name string `json:"name"`
}

type GroupListReq struct {
	BasePage
	Name string `form:"name,optional"`
}

type GroupListRes struct {
	Base
	Data GroupListData `json:"data"`
}

type GroupRemoveReq struct {
	Id string `json:"id"`
}

type GroupRemoveRes struct {
	Base
}

type GroupUpdateReq struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type GroupUpdateRes struct {
	Base
}

type HomeListInfo struct {
	Id       string `json:"id"`
	FileName string `json:"file_name"`
	FilePath string `json:"file_path"`
	W        int    `json:"w"`
	H        int    `json:"h"`
	Download int64  `json:"download"`
	View     int64  `json:"view"`
}

type HomeListReq struct {
	BasePage
}

type HomeListRes struct {
	Base
	Data HomeListResData `json:"data"`
}

type HomeListResData struct {
	Pc          []HomeListInfo `json:"pc"`
	Moa         []HomeListInfo `json:"moa"`
	HotPc       []HomeListInfo `json:"hot_pc"`
	DownloadMoa []HomeListInfo `json:"download_moa"`
	HotAvatar   []HomeListInfo `json:"hot_avatar"`
}

type ImageDeleteReq struct {
	BucketName string   `json:"bucket_name"`
	Id         string   `json:"id"`
	Paths      []string `json:"paths"`
}

type ImageDeleteRes struct {
	Base
}

type ImageInfo struct {
	BaseTime
	Id             string          `json:"id"`
	Hash           string          `json:"hash"`
	FileName       string          `json:"file_name"`
	OriginFileSize int64           `json:"origin_file_size"`
	FileSize       int64           `json:"file_size"`
	OriginType     string          `json:"origin_type"`
	FileType       string          `json:"file_type"`
	OriginFilePath string          `json:"origin_file_path"`
	FilePath       string          `json:"file_path"`
	Type           string          `json:"type"`
	W              int             `json:"w"`
	H              int             `json:"h"`
	Status         int             `json:"status"`
	UserId         string          `json:"user_id"`
	Download       int             `json:"download"`
	View           int             `json:"view"`
	Like           int             `json:"like"`
	Tags           []TagInfo       `json:"tags"`
	Category       []CategoryInfo  `json:"category"`
	Recommend      []RecommendInfo `json:"recommend"`
	Group          []GroupListInfo `json:"group"`
	Album          []Album         `json:"album"`
}

type ImageInfoByCategoryReq struct {
	BasePage
	Type       string `form:"type"`
	SortType   string `form:"sort_type,optional"`
	CategoryId string `form:"category_id,optional"`
}

type ImageInfoByCategoryRes struct {
	Base
	Data ImageInfoByCategoryResdata `json:"data"`
}

type ImageInfoByCategoryResdata struct {
	BaseRecord
	Records []ImageInfoCategory `json:"records"`
}

type ImageInfoByGroupReq struct {
	GroupId string `form:"group_id"`
	Type    string `form:"type"`
}

type ImageInfoByGroupRes struct {
	Base
	Data ImageInfoByGroupResdata `json:"data"`
}

type ImageInfoByGroupResdata struct {
	Records []ImageInfoGroup `json:"records"`
}

type ImageInfoByHotReq struct {
	BasePage
	Type string `form:"type"`
}

type ImageInfoByHotRes struct {
	Base
	Data ImageInfoByHotResdata `json:"data"`
}

type ImageInfoByHotResdata struct {
	BaseRecord
	Records []ImageInfoHot `json:"records"`
}

type ImageInfoByIdReq struct {
	Id string `form:"id"`
}

type ImageInfoByIdRes struct {
	Base
	Data ImageInfo `json:"data"`
}

type ImageInfoCategory struct {
	BaseTime
	Id       string `json:"id"`
	FileName string `json:"file_name"`
	FilePath string `json:"file_path"`
	W        int    `json:"w"`
	H        int    `json:"h"`
	Download int    `json:"download"`
	View     int    `json:"view"`
}

type ImageInfoGroup struct {
	BaseTime
	Id       string `json:"id"`
	FileName string `json:"file_name"`
	FilePath string `json:"file_path"`
	W        int    `json:"w"`
	H        int    `json:"h"`
}

type ImageInfoHot struct {
	BaseTime
	Id       string `json:"id"`
	FileName string `json:"file_name"`
	FilePath string `json:"file_path"`
	W        int    `json:"w"`
	H        int    `json:"h"`
}

type ImageInfoReq struct {
	BasePage
	FileName string `form:"file_name,optional"`
	Type     string `form:"type,optional"`
	Status   int    `form:"status,optional"`
}

type ImageInfoRes struct {
	Base
	Data ImageInfoResdata `json:"data"`
}

type ImageInfoResdata struct {
	BaseRecord
	Records []ImageInfo `json:"records"`
}

type ImageSummaryReq struct {
}

type ImageSummaryRes struct {
	Base
	Data ImageSummaryResdata `json:"data"`
}

type ImageSummaryResdata struct {
	Pc  int64 `json:"pc"`
	Moa int64 `json:"moa"`
}

type ImageSummaryUpdateReq struct {
	Id   string `json:"id"`
	Type string `json:"type,options=download|view"`
}

type ImageSummaryUpdateRes struct {
	Base
}

type ImageUpdateReq struct {
	Id        string   `json:"id"`
	FileName  string   `json:"file_name"`
	Type      string   `json:"type"`
	Status    int      `json:"status"`
	Tags      []string `json:"tags,optional"`
	Category  []string `json:"category,optional"`
	Recommend []string `json:"recommend,optional"`
	Group     []string `json:"group,optional"`
	Album     []string `json:"album,optional"`
}

type ImageUpdateRes struct {
	Base
}

type ImageUploadReq struct {
	FileName   string `form:"file_name"`
	Type       string `form:"type,optional"`
	RootDir    string `form:"root_dir"`
	Dir        string `form:"dir"`
	BucketName string `form:"bucket_name"`
	Quality    uint32 `form:"quality"`
	Status     int    `form:"status"`
	Tags       string `form:"tags,optional"`
	Category   string `form:"category,optional"`
	Recommend  string `form:"recommend,optional"`
	Group      string `form:"group,optional"`
	Album      string `form:"album,optional"`
}

type ImageUploadRes struct {
	Base
	Data ImageUploadResdata `json:"data"`
}

type ImageUploadResdata struct {
	Id         string `json:"id"`
	FileName   string `json:"file_name"`
	Path       string `json:"path"`
	OriginPath string `json:"origin_path"`
}

type LikeCreateOrUpdateReq struct {
	UploadId string `json:"upload_id"`
	Type     string `json:"type"`
	Status   bool   `json:"status"`
}

type LikeCreateOrUpdateRes struct {
	Base
}

type LikeListReq struct {
	UploadId string `form:"upload_id"`
}

type LikeListRes struct {
	Base
	Data []string `json:"data"`
}

type LikeNumReq struct {
	UploadId string `form:"upload_id"`
}

type LikeNumRes struct {
	Base
	Data LikeNumResData `json:"data"`
}

type LikeNumResData struct {
	Num int64 `json:"num"`
}

type LikeRemoveReq struct {
	Id string `json:"id"`
}

type LikeRemoveRes struct {
	Base
}

type PostCreateData struct {
	Id string `json:"id"`
}

type PostCreateReq struct {
	Title    string `json:"title"`
	Content  string `json:"content,optional"`
	ImageIds string `json:"image_ids"` // 逗号分隔
}

type PostCreateRes struct {
	Base
	Data PostCreateData `json:"data"`
}

type PostDeleteReq struct {
	Id string `json:"id"`
}

type PostDeleteRes struct {
	Base
}

type PostDetailReq struct {
	Id string `form:"id"`
}

type PostDetailRes struct {
	Base
	Data PostFeedInfo `json:"data"`
}

type PostFeedData struct {
	BaseRecord
	Records []PostFeedInfo `json:"records"`
}

type PostFeedInfo struct {
	BaseTime
	Id           string          `json:"id"`
	Title        string          `json:"title"`
	Content      string          `json:"content"`
	Images       []PostImageInfo `json:"images"`
	UserInfo     PostUserInfo    `json:"user_info"`
	LikeCount    int64           `json:"like_count"`
	IsLiked      bool            `json:"is_liked"`
	CommentCount int64           `json:"comment_count"`
	Status       int             `json:"status"`
	RejectReason string          `json:"reject_reason"`
}

type PostFeedReq struct {
	BasePage
	Sort string `form:"sort,optional"` // "hot" | "new", default "new"
}

type PostFeedRes struct {
	Base
	Data PostFeedData `json:"data"`
}

type PostImageInfo struct {
	Id       string `json:"id"`
	FilePath string `json:"file_path"`
	FileName string `json:"file_name"`
	W        int    `json:"w"`
	H        int    `json:"h"`
}

type PostReviewListData struct {
	BaseRecord
	Records []PostReviewListItem `json:"records"`
}

type PostReviewListItem struct {
	BaseTime
	Id           string          `json:"id"`
	Title        string          `json:"title"`
	Content      string          `json:"content"`
	ImageIds     string          `json:"image_ids"`
	Images       []PostImageInfo `json:"images"`
	Status       int             `json:"status"`
	RejectReason string          `json:"reject_reason"`
	UserInfo     PostUserInfo    `json:"user_info"`
}

type PostReviewListReq struct {
	BasePage
	Status int `form:"status,optional"` // 0=全部 2=待审核 1=已通过 -1=已拒绝
}

type PostReviewListRes struct {
	Base
	Data PostReviewListData `json:"data"`
}

type PostReviewUpdateReq struct {
	Id           string `json:"id"`
	Status       int    `json:"status"` // 1=通过 -1=拒绝
	RejectReason string `json:"reject_reason,optional"`
}

type PostReviewUpdateRes struct {
	Base
}

type PostUserInfo struct {
	Id       string `json:"id"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}

type RecommendCreateReq struct {
	Name string `json:"name"`
	Sort int    `json:"sort":"sort"`
}

type RecommendCreateRes struct {
	Base
}

type RecommendInfo struct {
	BaseRecord
	Id   string `json:"id"`
	Name string `json:"name"`
	Sort int    `json:"sort"`
}

type RecommendInfoData struct {
	BaseRecord
	Records []RecommendInfo `json:"records"`
}

type RecommendInfoReq struct {
	BasePage
	Name string `form:"name,optional"`
}

type RecommendInfoRes struct {
	Base
	Data RecommendInfoData `json:"data"`
}

type RecommendListInfo struct {
	BaseTime
	Id       string `json:"id"`
	FilePath string `json:"file_path"`
	FileName string `json:"file_name"`
}

type RecommendListReq struct {
	BasePage
	Id   string `form:"id"`
	Type string `form:"type"`
}

type RecommendListRes struct {
	Base
	Data RecommendListResData `json:"data"`
}

type RecommendListResData struct {
	BaseRecord
	Records []RecommendListInfo `json:"records"`
}

type RecommendRemoveReq struct {
	Id string `json:"id"`
}

type RecommendRemoveRes struct {
	Base
}

type RecommendSortInfo struct {
	Id   string `json:"id"`
	Sort int    `json:"sort"`
}

type RecommendSortReq struct {
	SortData []RecommendSortInfo `json:"sort_data"`
}

type RecommendSortRes struct {
	Base
}

type RecommendUpdateReq struct {
	Id   string `json:"id"`
	Name string `json:"name"`
	Sort int    `json:"sort"`
}

type RecommendUpdateRes struct {
	Base
}

type RemoveAllDownloadRecordRes struct {
	Base
}

type RemoveAllLikeRecordRes struct {
	Base
}

type RemoveTagReq struct {
	Id string `json:"id"`
}

type RemoveTagRes struct {
	Base
}

type SearchHotKeywordsData struct {
	BaseRecord
	Records []SearchHotKeywordsInfo `json:"records"`
}

type SearchHotKeywordsInfo struct {
	BaseTime
	Id          string `json:"id"`
	Keywords    string `json:"keywords" form:"keywords"`
	SearchCount int64  `json:"search_count" form:"search_count"`
}

type SearchHotKeywordsReq struct {
	BasePage
}

type SearchHotKeywordsRes struct {
	Base
	Data SearchHotKeywordsData `json:"data"`
}

type SearchListData struct {
	BaseRecord
	Records []SearchListInfo `json:"records"`
}

type SearchListInfo struct {
	BaseTime
	Id       string `json:"id"`
	FileName string `json:"file_name" form:"file_name"`
	FilePath string `json:"file_path" form:"file_path"`
	W        int    `json:"w" form:"w"`
	H        int    `json:"h" form:"h"`
	Download int    `json:"download" form:"download"`
	View     int    `json:"view" form:"view"`
}

type SearchListReq struct {
	BasePage
	Keywords string `form:"keywords"`
	Type     string `form:"type"`
}

type SearchListRes struct {
	Base
	Data SearchListData `json:"data"`
}

type SignInByAppleReq struct {
	AppleId string `json:"apple_id"`
	Email   string `json:"email,optional"`
	Name    string `json:"name,optional"`
}

type SignInByAppleRes struct {
	Base
	Data SignInByAppleResData `json:"data"`
}

type SignInByAppleResData struct {
	Token    string                `json:"token"`
	UserInfo SignInByAppleUserInfo `json:"user_info"`
}

type SignInByAppleUserInfo struct {
	Id       string `json:"id"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}

type SignInByQqReq struct {
	Code string `form:"code"`
}

type SignInByQqRes struct {
	Base
	Data SignInByQqResData `json:"data"`
}

type SignInByQqResData struct {
	Token    string             `json:"token"`
	UserInfo SignInByQqUserInfo `json:"user_info"`
}

type SignInByQqUrlRes struct {
	Base
	Data SignInByQqUrlResData `json:"data"`
}

type SignInByQqUrlResData struct {
	Url   string `json:"url"`
	State string `json:"state"`
}

type SignInByQqUserInfo struct {
	Id       string `json:"id"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}

type SignInByWechatReq struct {
	Code string `json:"code"`
}

type SignInByWechatRes struct {
	Base
	Data SignInByWechatResData `json:"data"`
}

type SignInByWechatResData struct {
	Token    string                 `json:"token"`
	UserInfo SignInByWechatUserInfo `json:"user_info"`
}

type SignInByWechatUserInfo struct {
	Id       string `json:"id"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}

type SignInReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type SignInRes struct {
	Base
	Data SignInResData `json:"data"`
}

type SignInResData struct {
	Token    string                `json:"token"`
	UserInfo SignInResDataUserInfo `json:"user_info"`
}

type SignInResDataUserInfo struct {
	Id       string `json:"id"`
	Username string `json:"username"`
	Motto    string `json:"motto"`
	Address  string `json:"address"`
	Tel      string `json:"tel"`
	Email    string `json:"email"`
	QQ       string `json:"qq"`
	Wechat   string `json:"wechat"`
	GitHub   string `json:"git_hub"`
	Role     string `json:"role"`
	Avatar   string `json:"avatar"`
	Cover    string `json:"cover"`
}

type SignUpCodeReq struct {
	Account string `json:"account"`
}

type SignUpCodeRes struct {
	Base
}

type SignUpReq struct {
	Account  string `json:"account"`
	Username string `json:"username"`
	Password string `json:"password"`
	Code     string `json:"code"`
}

type SignUpRes struct {
	Base
}

type SitemapReq struct {
	BasePage
	Type string `form:"type"`
}

type SitemapRes struct {
	Base
	Data SitemapResData `json:"data"`
}

type SitemapResData struct {
	BaseRecord
	Records []string `json:"records"`
}

type TagInfo struct {
	BaseTime
	Id   string `json:"id"`
	Name string `json:"name"`
	Type string `json:"type"`
	Sort int    `json:"sort"`
}

type TagInfoReq struct {
	BasePage
	Name string `form:"name,optional"`
	Type string `form:"type,optional"`
}

type TagInfoRes struct {
	Base
	Data TagInfoResData `json:"data"`
}

type TagInfoResData struct {
	BaseRecord
	Records []TagInfo `json:"records"`
}

type TagSortInfo struct {
	Id   string `json:"id"`
	Sort int    `json:"sort"`
}

type TagSortReq struct {
	SortData []TagSortInfo `json:"sort_data"`
}

type TagSortRes struct {
	Base
}

type UpdateTagReq struct {
	Id   string `json:"id"`
	Name string `json:"name"`
	Type string `json:"type"`
	Sort int    `json:"sort"`
}

type UpdateTagRes struct {
	Base
}

type UpdateUserInfoReq struct {
	Avatar   string `json:"avatar,optional"`
	Cover    string `json:"cover,optional"`
	Username string `json:"username,optional"`
	Motto    string `json:"motto,optional"`
}

type UpdateUserInfoRes struct {
	Base
}

type UserCommentListData struct {
	BaseRecord
	Records []UserCommentListItem `json:"records"`
}

type UserCommentListItem struct {
	BaseTime
	Id           string `json:"id"`
	PostId       string `json:"post_id"`
	PostTitle    string `json:"post_title"`
	Content      string `json:"content"`
	Status       int    `json:"status"`
	RejectReason string `json:"reject_reason"`
}

type UserCommentListReq struct {
	BasePage
}

type UserCommentListRes struct {
	Base
	Data UserCommentListData `json:"data"`
}

type UserDiscoverListData struct {
	BaseRecord
	Records []UserDiscoverListInfo `json:"records"`
}

type UserDiscoverListImages struct {
	Id       string `json:"id"`
	FilePath string `json:"file_path"`
	FileName string `json:"file_name"`
	W        int    `json:"w"`
	H        int    `json:"h"`
	Type     string `json:"type"`
}

type UserDiscoverListInfo struct {
	BaseTime
	Id       string                   `json:"id"`
	Title    string                   `json:"title"`
	Subtitle string                   `json:"subtitle"`
	Status   int                      `json:"status"`
	Images   []UserDiscoverListImages `json:"images"`
	UserInfo UserDiscoverUserInfo     `json:"user_info"`
}

type UserDiscoverListReq struct {
	BasePage
	Status int `form:"status,optional"`
}

type UserDiscoverListRes struct {
	Base
	Data UserDiscoverListData `json:"data"`
}

type UserDiscoverUserInfo struct {
	Id       string `json:"id"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}

type UserDownloadAndLikeSummaryData struct {
	Download int64 `json:"download"`
	Like     int64 `json:"like"`
	Discover int64 `json:"discover"`
	Block    int64 `json:"block"`
}

type UserDownloadAndLikeSummaryRes struct {
	Base
	Data UserDownloadAndLikeSummaryData `json:"data"`
}

type UserInfoReq struct {
}

type UserInfoRes struct {
	Base
	Data UserInfoResData `json:"data"`
}

type UserInfoResData struct {
	Id       string `json:"id"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
	Cover    string `json:"cover"`
	Motto    string `json:"motto"`
	Role     string `json:"role"`
}

type UserLikeListData struct {
	BaseRecord
	Records []UserLikeListRecord `json:"records"`
}

type UserLikeListRecord struct {
	BaseTime
	Id       string `json:"id"`
	FileId   string `json:"file_id"`
	FilePath string `json:"file_path"`
	FileName string `json:"file_name"`
	W        int    `json:"w"`
	H        int    `json:"h"`
	Type     string `json:"type"`
}

type UserLikeListReq struct {
	BasePage
	Type string `form:"type,optional"`
}

type UserLikeListRes struct {
	Base
	Data UserLikeListData `json:"data"`
}

type UserLikePostListData struct {
	BaseRecord
	Records []UserLikePostListItem `json:"records"`
}

type UserLikePostListItem struct {
	BaseTime
	Id           string `json:"id"`
	PostId       string `json:"post_id"`
	Title        string `json:"title"`
	Content      string `json:"content"`
	CoverPath    string `json:"cover_path"`
	LikeCount    int64  `json:"like_count"`
	CommentCount int64  `json:"comment_count"`
}

type UserLikePostListReq struct {
	BasePage
}

type UserLikePostListRes struct {
	Base
	Data UserLikePostListData `json:"data"`
}

type UserListData struct {
	BaseRecord
	Records []UserListInfo `json:"records"`
}

type UserListInfo struct {
	BaseTime
	Id       string `json:"id"`
	Username string `json:"username"`
	Account  string `json:"account"`
	Avatar   string `json:"avatar"`
	Role     string `json:"role"`
	Address  string `json:"address"`
	Tel      string `json:"tel"`
	Email    string `json:"email"`
	QQ       string `json:"qq"`
	Wechat   string `json:"wechat"`
	GitHub   string `json:"git_hub"`
	Motto    string `json:"motto"`
	Cover    string `json:"cover"`
}

type UserListReq struct {
	BasePage
	Username string `form:"username,optional"`
	Account  string `form:"account,optional"`
	Role     string `form:"role,optional"`
}

type UserListRes struct {
	Base
	Data UserListData `json:"data"`
}

type UserPostListReq struct {
	BasePage
	UserId string `form:"user_id"`
}

type UserPostListRes struct {
	Base
	Data PostFeedData `json:"data"`
}

type UserProfileData struct {
	UserInfo UserProfileInfo  `json:"user_info"`
	Stats    UserProfileStats `json:"stats"`
}

type UserProfileInfo struct {
	Id       string `json:"id"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
	Cover    string `json:"cover"`
	Motto    string `json:"motto"`
}

type UserProfileReq struct {
	UserId string `form:"user_id"`
}

type UserProfileRes struct {
	Base
	Data UserProfileData `json:"data"`
}

type UserProfileStats struct {
	UploadCount   int64 `json:"upload_count"`
	LikeCount     int64 `json:"like_count"`
	DownloadCount int64 `json:"download_count"`
}

type UserStatsData struct {
	PostCount         int64 `json:"post_count"`
	LikeReceivedCount int64 `json:"like_received_count"`
	CommentCount      int64 `json:"comment_count"`
	DownloadCount     int64 `json:"download_count"`
}

type UserStatsReq struct {
}

type UserStatsRes struct {
	Base
	Data UserStatsData `json:"data"`
}
